import Link from "next/link";
import Head from "next/head";
/*This page renders the contact page*/

const contact = () => {
  return <>
    <Head>
      <title>Gift Lehobye | Contact </title>
      <meta name="description" content="Generated by create next app" />
    </Head>

    <section className="contact" id="contact" style={{ marginTop: "50px" }}>
      <h1 className="section-heading">
        contact <span>details</span>
      </h1>
      <div className="container">
        <p>
          Feel free to contact me with any job opportunities and
          collaborations preferably contact me via email or inbox me on
          Linkedin so I dont miss your message.
        </p>
        <div className="list">
          <ul>
            <li>
              <Link
                href="https://www.linkedin.com/in/gift-lehobye/"
                passhref="true"
                legacyBehavior>
                <a target="_blank" className="contact-wrapper">
                  <i className="bi bi-linkedin" />
                  Gift Lehobye
                </a>
              </Link>
            </li>
            <li>
              <Link href="mailto:giftlehobye@gmail.com" passhref="true" legacyBehavior>
                <a target="_blank" className="contact-wrapper">
                  <i className="bi bi-envelope-open-fill" />
                  giftlehobye@gmail.com
                </a>
              </Link>
            </li>
            <li>
              <Link href="https://github.com/g1f7" passhref="true" legacyBehavior>
                <a target="_blank" className="contact-wrapper">
                  <i className="bi bi-github" />
                  Gift Lehobye
                </a>
              </Link>
            </li>
            <li>
              <Link href="https://www.instagram.com/_giftaustin_/" passhref="true" legacyBehavior>
                <a target="_blank" className="contact-wrapper">
                  <i className="bi bi-instagram" />
                  Instagram
                </a>
              </Link>
            </li>
          </ul>
        </div>
      </div>

      <style jsx>{`
        .contact .container {
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          gap: 40px;
        }

        .contact .container .list {
          color: var(--primary-color);
          line-height: 51px;
          cursor: pointer;
        }

        .contact .container .list a i {
          color: var(--primary-color);
        }

        .contact p {
          padding: 10px;
          line-height: 30px;
          font-family: "Open Sans", sans-serif;
          font-size: 16px;
          font-weight: 500;
          max-width: 800px;
          text-align: center;
        }

        .contact-wrapper::before {
          content: "";
          display: inline-block;
          background-image: url(./img/dot.png);
          background-position: center;
          background-repeat: no-repeat;
          background-size: cover;
          width: 0.5em;
          height: 0.5em;
        }

        .contact-wrapper {
          font-size: 20px;
          color: #fff;
        }

        .contact-wrapper i {
          margin: 0 15px;
        }
      `}</style>
    </section>
  </>;
};

export default contact;
